main/urls.py
from django.urls import path
from django.conf.urls import url


from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/',views.data_func, name='data'),
    path('signup/', views.signup, name='signup'),
    # path('register/', views.register, name='register'),

    
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

# @receiver(post_save, sender=User)
# def update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username', 'birth_date', 'password1', 'password2')


    def save(self, commit=True):
        user = super (SignUpForm , self ).save(commit=False)
        user.username = self.cleaned_data ['username']
        user.birth_date = self.cleaned_data ['birth_date']
        user.password1 = self.cleaned_data ['password1']
        user.password2 = self.cleaned_data ['password2']
        user.is_staff = True

        if commit :
            user.save()

        return user
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User


# # Create your forms here.

# class NewUserForm(UserCreationForm):
# 	email = forms.EmailField(required=True)

# 	class Meta:
# 		model = User
# 		fields = ("username", "email", "password1", "password2")

# 	def save(self, commit=True):
# 		user = super(NewUserForm, self).save(commit=False)
# 		user.email = self.cleaned_data['email']
# 		if commit:
# 			user.save()
# 		return user

main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import requests
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from main.forms import SignUpForm
def home(request):
    return render(request, 'main/home.html')

def data_func(request):
    arg= request.GET['q']
    url='https://www.googleapis.com/books/v1/volumes?q='+ arg
    req=requests.get(url)


    data= json.loads(req.content)

    if not request.user.is_authenticated:
        idx=0;
        for x in data['items']:
            del data['items'][idx]['volumeInfo']['imageLinks']['smallThumbnail']
            # del data['items'][idx]['volumeInfo']['authors']
            # del data['items'][idx]['volumeInfo']['publisher']
            # del data['items'][idx]['volumeInfo']['publishedDate']
            idx=idx+1
    return JsonResponse(data, safe=False)



def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            # user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'main/signup.html', {'form': form})

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title>Search</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="{%static 'js/script.js'%}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

{% endblock meta %}

{% block content %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>

      {% if user.is_authenticated %}
     
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Halo  {{user.get_username}}</a></li>
      <li><a href="/admin/logout/?next=/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
    {% else %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'main:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/admin/login/?next=/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
    {% endif %}


  </div>
</nav>
  <h1>Search here</h1>
  <input id="keyword" placeholder="Masukkan kata kunci">
 <table id="table"class="table table-borderless table-dark" border=1>
   <thead>
    <tr>
      <th scope="col" class="align-middle">No</th>
      <th scope="col" class="align-middle">Cover</th>
      <th scope="col" class="align-middle">Title</th>
      <th scope="col" class="align-middle">Authors</th>
      <th scope="col" class="align-middle">Publisher</th>
      <th scope="col" class="align-middle">Published Date</th>
  
     </tr>

   </thead>
   <tbody id="content"></tbody>
  
 </table>

{% endblock content %}

main/templates/main/register.html
{% extends "main/home.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

main/templates/main/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
 
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>